import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { dir } from "i18next";
import { languages } from "../../lib/i18n/settings";
import "../globals.css";
import { cn } from "@/lib/utils";
import LeftSidebar from "@/components/LeftSidebar";
import {ClerkProvider} from '@clerk/nextjs'

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export default function RootLayout({
  children,
  params: { lng },
}: Readonly<{
  children: React.ReactNode;
  params: {
    lng: string;
  };
}>) {
  return (
    <ClerkProvider>
      <html lang={lng} dir={dir(lng)}>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <div className="w-screen h-screen flex flex-row">
          <LeftSidebar />
          <div className="flex-1 p-8">{children}</div>
        </div>
      </body>
    </html>
    </ClerkProvider>
    
  );
}
